version: '3'
services:
  auth_db:
    image: mysql
    container_name: auth_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - auth_db:/data/db

  redis:
    image: redis
    container_name: token_blacklist
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  auth_db:
    driver: local