server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3309/auth_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
  cloud:
    vault:
      uri: ${VAULT_URI:http://localhost:8200}
      token: ${VAULT_TOKEN:my-root-token}
      kv:
        enabled: true
        backend: secret
        profile-separator: /
        default-context: auth-service
  config:
    import: vault://
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:leesout21@gmail.com}
    password: ${MAIL_PASSWORD:oihx vfuh pkbe stwn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  jwt:
    expiration-ms: ${EXPIRATION_TIME_MS:3600000} # 1 saat
    refresh-expiration-ms: ${REFRESH_EXPIRATION_TIME_MS:86400000} # 1 gün
    rsa:
      private-key: ${rsa-private-key:#{null}}
      public-key: ${rsa-public-key:#{null}}

graylog:
  host: ${GRAYLOG_HOST:localhost}
  port: ${GRAYLOG_PORT:12201}
