server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
  cloud:
    vault:
      uri: ${VAULT_URI:http://localhost:8200}
      token: ${VAULT_TOKEN:my-root-token}
      kv:
        enabled: true
        backend: secret
        profile-separator: /
        default-context: auth-service
  config:
    import: vault://
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  frontend:
    url: ${application.frontend-url}
  jwt:
    expiration-ms: ${jwt.expiration-ms}
    refresh-expiration-ms: ${jwt.refresh-expiration-ms}
    rsa:
      private-key: ${jwt.rsa-private-key:#{null}}
      public-key: ${jwt.rsa-public-key:#{null}}

graylog:
  host: ${graylog.host}
  port: ${graylog.port}
